services:
    erp.stripe.syncer.abstract_syncer:
        class: Erp\StripeBundle\Syncer\AbstractSyncer
        abstract:  true
        calls:
            - [setChargeSyncer, ['@erp.stripe.syncer.charge_syncer']]
            - [setInvoiceSyncer, ['@erp.stripe.syncer.invoice_syncer']]

    erp.stripe.syncer.charge_syncer:
        class: Erp\StripeBundle\Syncer\ChargeSyncer
        parent: erp.stripe.syncer.abstract_syncer

    erp.stripe.syncer.invoice_syncer:
        class: Erp\StripeBundle\Syncer\InvoiceSyncer
        parent: erp.stripe.syncer.abstract_syncer

    erp.stripe.syncer.webhook_syncer:
        class: Erp\StripeBundle\Syncer\WebhookSyncer
        parent: erp.stripe.syncer.abstract_syncer

    erp_stripe.event.event_guesser:
        class: Erp\StripeBundle\Event\EventGuesser
        arguments:
            - '%kernel.debug%'

    erp_stripe.event_listener.abstract_subscriber:
        abstract: true
        class:
        arguments:
            - '@doctrine'

    erp_stripe.event_listener.charge_subscriber:
        parent: erp_stripe.event_listener.abstract_subscriber
        class: Erp\StripeBundle\EventListener\ChargeSubscriber
        tags:
            - { name: kernel.event_subscriber }

    erp_stripe.event_listener.invoice_subscriber:
        parent: erp_stripe.event_listener.abstract_subscriber
        class: Erp\StripeBundle\EventListener\InvoiceSubscriber
        tags:
            - { name: kernel.event_subscriber }