parameters:
    paysimple.user_name: "APIUser44005"
    paysimple.api_secret_code: "xdqRjXlXMJPfEJcl5MLOhzeIEcSd3l4F0QwbS3HNsbswZBxd6Nzw5sxi6nqkmsUIuLCylebvS4WhSlzukvhHEwEl3Rf1PYqcf0utNdKbe7spXxpXdW7ENW0Diczg7vZ0"

    paysimple.api.endpoint.test: "https://sandbox-api.paysimple.com"
    paysimple.api.endpoint.live: "https://api.paysimple.com"

    paysimple.api.test_mode: false

    stripe.public_key: pk_test_pItb6gPjAbEqLnLcsC5gIYpG
    stripe.secret_key: sk_test_ajlUnDTI4WUVjU6gq8x3Rxe3