services:

    erp.payment.paysimple_service:
        class: Erp\PaymentBundle\Services\PaySimpleService
        arguments: [@service_container]

    erp.payment.stripe.client:
        class: Erp\PaymentBundle\Stripe\Client\Client
        arguments:
            - '%stripe.secret_key%'

    erp.payment.stripe.manager.abstract_manager:
        class: Erp\PaymentBundle\Stripe\Manager\AbstractManager
        abstract:  true
        arguments:
            - '@erp.payment.stripe.client'

    erp.payment.stripe.manager.customer_manager:
        class: Erp\PaymentBundle\Stripe\Manager\CustomerManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.plan_manager:
        class: Erp\PaymentBundle\Stripe\Manager\PlanManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.subscription_manager:
        class: Erp\PaymentBundle\Stripe\Manager\SubscriptionManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.account_manager:
        class: Erp\PaymentBundle\Stripe\Manager\AccountManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.token_manager:
        class: Erp\PaymentBundle\Stripe\Manager\TokenManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.charge_manager:
        class: Erp\PaymentBundle\Stripe\Manager\ChargeManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.stripe.manager.event_manager:
        class: Erp\PaymentBundle\Stripe\Manager\EventManager
        parent: erp.payment.stripe.manager.abstract_manager

    erp.payment.form.type.stripe_credit_card:
        class: Erp\PaymentBundle\Form\Type\StripeCreditCardType
        tags:
            - { name: form.type, alias: erp_stripe_credit_card }

    erp.payment.form.stripe_credit_card:
        class: Symfony\Component\Form\Form
        factory: 'form.factory:createNamed'
        arguments: ['erp_stripe_credit_card', 'erp_stripe_credit_card', null]

    erp.payment.form.type.stripe_bank_account:
        class: Erp\PaymentBundle\Form\Type\StripeBankAccountType
        tags:
            - { name: form.type, alias: erp_stripe_bank_account }

    erp.payment.form.stripe_bank_account:
        class: Symfony\Component\Form\Form
        factory: 'form.factory:createNamed'
        arguments: ['erp_stripe_credit_card', 'erp_stripe_bank_account', null]

    erp.payment.stripe.registry.form_registry:
        class: Erp\PaymentBundle\Stripe\Registry\FormRegistry
        arguments:
            - {cc: '@erp.payment.form.stripe_credit_card', ba: '@erp.payment.form.stripe_bank_account'}

    erp.payment.stripe.registry.model_registry:
        class: Erp\PaymentBundle\Stripe\Registry\ModelRegistry
        arguments:
            - {cc: 'Erp\PaymentBundle\Stripe\Model\CreditCard', ba: 'Erp\PaymentBundle\Stripe\Model\BankAccount'}

    erp.payment.stripe.manager.user_manager:
        class: Erp\PaymentBundle\Stripe\Manager\UserManager
        arguments:
            - '@erp.payment.stripe.manager.customer_manager'
            - '@phy_cache'

    erp.payment.entity.unit_settings_manager:
        class: Erp\PaymentBundle\Entity\UnitSettingsManager
        arguments:
            - '@doctrine'

    erp.payment.consumer.update_subscriptions:
        class: Erp\PaymentBundle\Consumer\UpdateSubscriptionsConsumer
        arguments:
            - '@doctrine'
            - '@erp.payment.stripe.manager.subscription_manager'

    erp.payment.stripe.provider.bank_account_payment_type_provider:
        class: 'Erp\PaymentBundle\Stripe\Provider\BankAccountPaymentTypeProvider'
        arguments:
            - '@erp.payment.stripe.manager.customer_manager'

    erp.payment.stripe.provider.credit_card_payment_type_provider:
        class: 'Erp\PaymentBundle\Stripe\Provider\CreditCardPaymentTypeProvider'
        arguments:
            - '@erp.payment.stripe.manager.customer_manager'

    erp.payment.stripe.provider.payment_type_registry:
        class: 'Erp\PaymentBundle\Stripe\Provider\PaymentTypeRegistry'
        arguments:
            -
                - '@erp.payment.stripe.provider.bank_account_payment_type_provider'
                - '@erp.payment.stripe.provider.credit_card_payment_type_provider'

    erp.payment.stripe.provider.payment_type_provider:
        class: 'Erp\PaymentBundle\Stripe\Provider\PaymentTypeProvider'
        arguments:
            - '@erp.payment.stripe.provider.payment_type_registry'

    erp.payment.plaid.service.abstract_service:
        class: 'Erp\PaymentBundle\Plaid\Service\AbstractService'
        arguments:
            - '@erp.curl'
        calls:
            - [setEnvironment, ['%plaid_env%']]
        abstract: true

    erp.payment.plaid.service.item:
        class: 'Erp\PaymentBundle\Plaid\Service\Item'
        parent: 'erp.payment.plaid.service.abstract_service'
        arguments:
            - '%plaid.client_id%'
            - '%plaid.secret_key%'

    erp.payment.plaid.service.processor:
        class: 'Erp\PaymentBundle\Plaid\Service\Processor'
        parent: 'erp.payment.plaid.service.abstract_service'
        arguments:
            - '%plaid.client_id%'
            - '%plaid.secret_key%'
