erp_site_homepage:
    path:     /
    defaults: { _controller: ErpSiteBundle:Index:index }

erp_site_send_invite_to_landlord:
    path:     /send-invite-landlord
    defaults: { _controller: ErpSiteBundle:Index:sendInviteToLandlord }
    options:
        expose: true
    methods: [GET, POST]

erp_site_contact_page:
    path: /contact
    defaults: { _controller: ErpSiteBundle:Index:contactPage }

erp_site_static_page:
    path: /{slug}
    defaults: { _controller: ErpSiteBundle:Index:staticPage }
