parameters:
    authentication_handler.class: Erp\UserBundle\Handler\AuthenticationHandler
    erp.users.administrator_service.class: Erp\UserBundle\Services\Administrator
    erp.users.landlor_service.class: Erp\UserBundle\Services\Landlord
    erp.users.landlord.form_registration.class: Erp\UserBundle\Form\Type\LandlordRegistrationFormType
    erp.users.form_reset_password.class: Erp\UserBundle\Form\Type\UserResetPasswordFormType
    erp.users.twig.user_extention.class: Erp\UserBundle\Twig\UserExtention
    erp.users.user.class: Erp\UserBundle\Services\UserService

services:
    authentication_handler:
        class:        %authentication_handler.class%
        arguments:    [@router, @security.context]

    erp.users.administrator_service:
        class:        %erp.users.administrator_service.class%
        arguments:    [@service_container]

    erp.users.landlor_service:
        class:        %erp.users.landlor_service.class%
        arguments:    [@service_container]

    erp.users.landlord.form_registration:
        class: %erp.users.landlord.form_registration.class%
        tags:
            - { name: form.type, alias: erp_users_landlord_form_registration }

    erp.users.form_reset_password:
        class: %erp.users.form_reset_password.class%
        tags:
            - { name: form.type, alias: erp_users_form_reset_password }

    erp.users.twig.user_extention:
        class: %erp.users.twig.user_extention.class%
        tags:
            -  { name: twig.extension }
        arguments: [@service_container]

    erp.users.user.service:
        class: %erp.users.user.class%
        arguments: [@service_container]
