parameters:
    erp.signature.docusign.class: Erp\SignatureBundle\Service\DocuSignService
    erp.signature.docusign_client.class: Erp\SignatureBundle\DocuSignClient\DocuSignClient

services:
    erp.signature.docusign.service:
        class: %erp.signature.docusign.class%
        arguments: [@service_container]

    erp.signature.docusign.client:
        class: %erp.signature.docusign_client.class%
        arguments: [@service_container]
        calls:
            - [initConfig]