services:
    erp_property_checker_property_checker:
        class: Erp\PropertyBundle\Checker\PropertyChecker

    erp_property_event_listener_property_entity_listener:
        class: 'Erp\PropertyBundle\EventListener\PropertyEntityListener'
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Erp\PropertyBundle\Entity\Property', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: 'Erp\PropertyBundle\Entity\Property', event: postUpdate }