services:
    erp_property.checker.property_checker:
        class: Erp\PropertyBundle\Checker\PropertyChecker

    erp_property.event_listener.property_entity_listener:
        class: 'Erp\PropertyBundle\EventListener\PropertyEntityListener'
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Erp\PropertyBundle\Entity\Property', event: postPersist }
            - { name: doctrine.orm.entity_listener, entity: 'Erp\PropertyBundle\Entity\Property', event: postUpdate }