services:
  # history
  erp_notification.history_entity_manager:
    class: Doctrine\Common\Persistence\ObjectManager
    factory: ["@doctrine", getManagerForClass]
    arguments:
      - Erp\NotificationBundle\Entity\History

  erp_notification.history_repository:
    class: Erp\NotificationBundle\Repository\HistoryRepository
    factory: ["@erp_notification.history_entity_manager", getRepository]
    arguments:
      - Erp\NotificationBundle\Entity\History

  erp_notification.history_manager:
    class: Erp\NotificationBundle\Services\History\HistoryManager
    arguments:
      - @erp_notification.history_repository
