erp_user_accounting:
    path:     /accounting.{_format}
    defaults:
        _controller: ErpUserBundle:Accounting:index
        _format: 'html'
    requirements:
        _format: 'html|pdf'
    methods: [GET, POST]
