erp_user_late_rent_payment_settings_update:
    path:     /late-rent-payment-settings/update/{user}
    defaults: { _controller: ErpUserBundle:LateRentPaymentSettings:update }
    methods: [GET, POST]
    requirements:
        user: \d+

erp_user_late_rent_payment_settings_create:
     path:     /late-rent-payment-settings/create/{user}
     defaults: { _controller: ErpUserBundle:LateRentPaymentSettings:create }
     methods: [GET, POST]
     requirements:
        user: \d+

erp_user_late_rent_payment_settings_allow_rent_payments_settings:
     path:     /late-rent-payment-settings/allow/{user}
     defaults: { _controller: ErpUserBundle:LateRentPaymentSettings:allowRentPayment }
     methods: [POST]
     requirements:
        userId: \d+