erp_user_late_rent_payment_update:
    path:     /late-rent-payment/update/{user}
    defaults: { _controller: ErpUserBundle:LateRentPayment:update }
    methods: [GET, POST]
    requirements:
        user: \d+

erp_user_late_rent_payment_create:
     path:     /late-rent-payment/create/{user}
     defaults: { _controller: ErpUserBundle:LateRentPayment:create }
     methods: [GET, POST]
     requirements:
        user: \d+


erp_user_late_rent_payment_remove:
     path:     /late-rent-payment/remove/{id}
     defaults: { _controller: ErpUserBundle:LateRentPayment:remove }
     methods: [POST, GET]
     requirements:
        id: \d+

erp_user_late_rent_payment_remove_user:
     path:     /late-rent-payment/user/remove/{id}
     defaults: { _controller: ErpUserBundle:LateRentPayment:removeUser }
     methods: [GET, DELETE]
     requirements:
        id: \d+