erp_user_late_rent_payment_update:
    path:     /late-rent-payment-settings/update/{user}
    defaults: { _controller: ErpUserBundle:LateRentPayment:update }
    methods: [GET, POST]
    requirements:
        user: \d+

erp_user_late_rent_payment_create:
     path:     /late-rent-payment-settings/create/{user}
     defaults: { _controller: ErpUserBundle:LateRentPayment:create }
     methods: [GET, POST]
     requirements:
        user: \d+


erp_user_late_rent_payment_remove:
     path:     /late-rent-payment-settings/remove/{id}
     defaults: { _controller: ErpUserBundle:LateRentPayment:remove }
     methods: [POST]
     requirements:
        user: \d+